# wrangler.toml
# This is the corrected configuration file for a Cloudflare Pages deployment.
# It includes the 'pages_build_output_dir' to make it valid for the Pages build system.

name = "mpl-invoice-manager"
compatibility_date = "2023-10-30"

# This property is required for Cloudflare Pages to correctly process the file
# and apply the database binding to your functions.
pages_build_output_dir = "./"

[[d1_databases]]
binding = "DB" # This is how the worker will access the database (env.DB)
database_name = "mpl-invoices"
# This ID is set to your specific D1 database.
database_id = "04f0df31-9bf2-41a5-b0d2-edaed76a87ce"
